### ISSUE TITLE
XeLaTeX support

### ISSUE THREAD

**Issue by white-gecko** [vtex-soft/texsupport.iospress-ds#1]
For me the example does not work with XeLaTeX. Is there some alternative documentclass for XeLaTeX? How can I use this style with XeLaTeX?

**Comment by mingiss** [comment]
Hello!

**Comment by mingiss** [comment]
I've added few extra definitions to avoid compilation errors under XeLaTeX:
https://github.com/vtex-soft/texsupport.iospress-ds/blob/master/iosart2x.cls
https://github.com/vtex-soft/texsupport.iospress-ds/blob/master/iosart2x.cfg
Nevertheless, there is no guarantee any problems will not arise in the future, because I'm not quite aware about compilation circumstances using XeLaTeX. Preferred compilers for our styles are LuaLaTeX, PDFLaTeX or even better plain LaTeX in DVI mode (the latter is used in our production workflow).
Regards, Mindaugas.
